name: Django CI

on:
  push:
    branches: [ "main" ]
    path:
      - 'django/**'
  pull_request:
    branches: [ "main" ]
    path:
      - 'django/**'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.7
      uses: actions/setup-python@v3
      with:
        python-version: 3.12.7
    - name: Install Dependencies
      working-directory: django
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      working-directory: django/petclinic_django
      run: |
        python manage.py test
